// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nxb.Data;

#nullable disable

namespace Nxb.Migrations.Student
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nxb.Models.Marks", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("SubjectId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Marks", t =>
                        {
                            t.HasCheckConstraint("CK_Marks_Score", "[Score] >= 0 AND [Score] <= 10");
                        });

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            StudentId = 1,
                            Score = 8.5
                        },
                        new
                        {
                            SubjectId = 2,
                            StudentId = 1,
                            Score = 9.0
                        },
                        new
                        {
                            SubjectId = 1,
                            StudentId = 2,
                            Score = 7.5
                        },
                        new
                        {
                            SubjectId = 3,
                            StudentId = 2,
                            Score = 8.0
                        },
                        new
                        {
                            SubjectId = 2,
                            StudentId = 3,
                            Score = 8.0
                        },
                        new
                        {
                            SubjectId = 3,
                            StudentId = 4,
                            Score = 7.0
                        });
                });

            modelBuilder.Entity("Nxb.Models.StdClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("StdClass");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassName = "K24CNT2"
                        },
                        new
                        {
                            Id = 2,
                            ClassName = "K24CNT3"
                        });
                });

            modelBuilder.Entity("Nxb.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("StudentAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("StudentAvatar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StudentBirthday")
                        .HasColumnType("date");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentEmail")
                        .IsUnique();

                    b.HasIndex("StudentPhone")
                        .IsUnique();

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassId = 1,
                            StudentAddress = "Hà Nội",
                            StudentAvatar = "demo.png",
                            StudentBirthday = new DateTime(2006, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "an@example.com",
                            StudentName = "Nguyễn An",
                            StudentPhone = "0900000001"
                        },
                        new
                        {
                            Id = 2,
                            ClassId = 1,
                            StudentAddress = "Hải Phòng",
                            StudentAvatar = "demo.png",
                            StudentBirthday = new DateTime(2006, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "binh@example.com",
                            StudentName = "Trần Bình",
                            StudentPhone = "0900000002"
                        },
                        new
                        {
                            Id = 3,
                            ClassId = 2,
                            StudentAddress = "Đà Nẵng",
                            StudentAvatar = "demo.png",
                            StudentBirthday = new DateTime(2006, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "chi@example.com",
                            StudentName = "Lê Chi",
                            StudentPhone = "0900000003"
                        },
                        new
                        {
                            Id = 4,
                            ClassId = 2,
                            StudentAddress = "Hà Nội",
                            StudentAvatar = "demo.png",
                            StudentBirthday = new DateTime(2006, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentEmail = "dung@example.com",
                            StudentName = "Phạm Dũng",
                            StudentPhone = "0900000004"
                        });
                });

            modelBuilder.Entity("Nxb.Models.Subjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectName")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectName = "Lập trình ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            SubjectName = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            Id = 3,
                            SubjectName = "Tiếng Anh"
                        });
                });

            modelBuilder.Entity("Nxb.Models.Marks", b =>
                {
                    b.HasOne("Nxb.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nxb.Models.Subjects", "Subject")
                        .WithMany("Marks")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Nxb.Models.Student", b =>
                {
                    b.HasOne("Nxb.Models.StdClass", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Nxb.Models.StdClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Nxb.Models.Student", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Nxb.Models.Subjects", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
