// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nxb.Data;

#nullable disable

namespace Nxb.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930035114_InitialNxb")]
    partial class InitialNxb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nxb.Models.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Banner", t =>
                        {
                            t.HasCheckConstraint("CK_Banner_Status", "[Status] IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Khám phá sản phẩm mới tại Nxb",
                            Image = "demo-1.png",
                            Name = "Bộ sưu tập mới",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các mẫu túi và balo dành cho bạn",
                            Image = "demo-2.png",
                            Name = "Ưu đãi hôm nay",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bật trạng thái để hiển thị trên trang chủ",
                            Image = "demo-1.png",
                            Name = "Banner đang ẩn",
                            Status = (byte)0
                        });
                });

            modelBuilder.Entity("Nxb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Category", t =>
                        {
                            t.HasCheckConstraint("CK_Category_Status", "[Status] IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Túi xách",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Balo",
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phụ kiện",
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Nxb.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("SalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Price", "[Price] >= 0 AND [SalePrice] >= 0 AND [SalePrice] <= [Price]");

                            t.HasCheckConstraint("CK_Product_Status", "[Status] IN (0,1)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-1.png",
                            Name = "Túi xách đen",
                            Price = 500000f,
                            SalePrice = 450000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-2.png",
                            Name = "Túi xách đỏ",
                            Price = 550000f,
                            SalePrice = 500000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-3.png",
                            Name = "Túi xách xanh",
                            Price = 600000f,
                            SalePrice = 550000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-4.png",
                            Name = "Túi xách nâu",
                            Price = 650000f,
                            SalePrice = 600000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-5.png",
                            Name = "Balo đen",
                            Price = 700000f,
                            SalePrice = 650000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-6.png",
                            Name = "Balo xanh",
                            Price = 750000f,
                            SalePrice = 700000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-7.png",
                            Name = "Ví nhỏ",
                            Price = 800000f,
                            SalePrice = 750000f,
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2026, 9, 30, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Descriptions = "Sản phẩm mẫu dùng để thực hành thêm, xem, sửa và xóa.",
                            Image = "demo-8.png",
                            Name = "Túi mini",
                            Price = 850000f,
                            SalePrice = 800000f,
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Nxb.Models.Product", b =>
                {
                    b.HasOne("Nxb.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Nxb.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
